import Head from 'next/head'

type Props = {
	title: string
}

export default function Home({ title = 'Boilerplate' }: Props) {
	return (
		<div>
			<Head>
				<title>{title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
		</div>
	)
}
